name: psgbot
dependencies:
  - base == 4.*
  - containers == 0.6.*
  - data-fix == 0.3.*
  - random == 1.2.*
  - parsec == 3.1.*

executables:
  psgbot:
    main: Main.hs
    source-dirs:
      - src
      - app

tests:
  psgbot-spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec
      - parsec == 3.1.*
    build-tools: hspec-discover
